export const goleiros = [
    {
        nome: "Weverton",
        posicao: "goleiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 1,
    },
    {
        nome: "Everson",
        posicao: "goleiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 2,
    },
    {
        nome: "Rossi",
        posicao: "goleiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 3,
    },
    {
        nome: "Hugo",
        posicao: "goleiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 4,
    },
    {
        nome: "Joao Ricardo",
        posicao: "goleiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 5,
    },
    {
        nome: "Leo Linck",
        posicao: "goleiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
        id: 6,
    },
    {
        nome: "Sergio Romero",
        posicao: "goleiro",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 7,
    },
    {
        nome: "Armani",
        posicao: "goleiro",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 8,
    },
];

export const laterais = [
    {
        nome: "Marcos Rocha",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 10,
    },
    {
        nome: "Piquerez",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 11,
    },
    {
        nome: "G. Arana",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 24,
    },
    {
        nome: "Mariano",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 12,
    },
    {
        nome: "Varela",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 13,
    },
    {
        nome: "Alex Sandro",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 14,
    },
    {
        nome: "Fagner",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 15,
    },
    {
        nome: "Lucas Piton",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 16,
    },
    {
        nome: "Abner Vinícius",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
        id: 17,
    },
    {
        nome: "Khellven",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
        id: 18,
    },
    {
        nome: "Eros Mancuso",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 19,
    },
    {
        nome: "Yago Pikachu",
        posicao: "lateral",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 20,
    },
    {
        nome: "Jonathan Fabra",
        posicao: "lateral",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 21,
    },
    {
        nome: "Jorge Figal",
        posicao: "lateral",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 22,
    },
    {
        nome: "Milton Casco",
        posicao: "lateral",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 23,
    },
];

export const zagueiros = [
    {
        nome: "Paulo Diaz",
        posicao: "zagueiro",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 25,
    },
    {
        nome: "Emanuel Mammana",
        posicao: "zagueiro",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 26,
    },
    {
        nome: "Marcos Rojo",
        posicao: "zagueiro",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 27,
    },
    {
        nome: "David Luiz",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 28,
    },
    {
        nome: "Leo Pereira",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 29,
    },
    {
        nome: "Caetano",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 30,
    },
    {
        nome: "Andre Ramalho",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 31,
    },
    {
        nome: "G. Gomez",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 32,
    },
    {
        nome: "Murillo",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 33,
    },
    {
        nome: "Tinga",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 34,
    },
    {
        nome: "Alonso",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 35,
    },
    {
        nome: "Lyanco",
        posicao: "zagueiro",
        clube: "BRA",
        imagem: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 36,
    },
];

export const meioCampistas = [
    {
        nome: "Enzo Pérez",
        posicao: "meio-campista",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 37,
    },
    {
        nome: "Zaracho",
        posicao: "meio-campista",
        clube: "ARG",
        imagem: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 38,
    },
    {
        nome: "Gerson",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 39,
    },
    {
        nome: "Everton Ribeiro",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 40,
    },
    {
        nome: "Igor Coronado",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 41,
    },
    {
        nome: "Rodrigo Garro",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 42,
    },
    {
        nome: "Zé Rafael",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 43,
    },
    {
        nome: "Raphael Veiga",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 44,
    },
    {
        nome: "Vitor Bueno",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 45,
    },
    {
        nome: "Caio Alexandre",
        posicao: "meio-campista",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 46,
    },
    {
        nome: "Fernández",
        posicao: "meio-campista",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 47,
    },
    {
        nome: "Ramírez",
        posicao: "meio-campista",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 48,
    },
];

export const atacantes = [
    {
        nome: "Pedro",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 49,
    },
    {
        nome: "Gabriel Barbosa (Gabigol)",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 50,
    },
    {
        nome: "Memphis Depay",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 51,
    },
    {
        nome: "Yuri Alberto",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 52,
    },
    {
        nome: "Dudu",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 53,
    },
    {
        nome: "Rony",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 54,
    },
    {
        nome: "Luciano",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/nPccDYP/saopaulo-bra.png",
        id: 55,
    },
    {
        nome: "Calleri",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/nPccDYP/saopaulo-bra.png",
        id: 56,
    },
    {
        nome: "Moisés",
        posicao: "atacante",
        clube: "BRA",
        imagem: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 57,
    },
    {
        nome: "Pochettino",
        posicao: "atacante",
        clube: "ARG",
        imagem: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 58,
    },
    {
        nome: "Borja",
        posicao: "atacante",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 59,
    },
    {
        nome: "Beltrán",
        posicao: "atacante",
        clube: "ARG",
        imagem: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 60,
    },
];
