export const goalkeepers = [
    {
        name: "Weverton",
        position: "goalkeeper",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 1,
    },
    {
        name: "Everson",
        position: "goalkeeper",
        club: "BRA",
        image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 2,
    },
    {
        name: "Rossi",
        position: "goalkeeper",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 3,
    },
    {
        name: "Hugo",
        position: "goalkeeper",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 4,
    },
    {
        name: "Joao Ricardo",
        position: "goalkeeper",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 5,
    },
    {
        name: "Leo Linck",
        position: "goalkeeper",
        club: "BRA",
        image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
        id: 6,
    },
    {
        name: "Sergio Romero",
        position: "goalkeeper",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 7,
    },
    {
        name: "Armani",
        position: "goalkeeper",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 8,
    },
];

export const sides = [
    {
        name: "Marcos Rocha",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 10,
    },
    {
        name: "Piquerez",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 11,
    },
    {
        name: "G. Arana",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 24,
    },
    {
        name: "Mariano",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 12,
    },
    {
        name: "Varela",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 13,
    },
    {
        name: "Alex Sandro",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 14,
    },
    {
        name: "Fagner",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 15,
    },
    {
        name: "Lucas Piton",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 16,
    },
    {
        name: "Abner Vinícius",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
        id: 17,
    },
    {
        name: "Khellven",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
        id: 18,
    },
    {
        name: "Eros Mancuso",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 19,
    },
    {
        name: "Yago Pikachu",
        position: "side",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 20,
    },
    {
        name: "Jonathan Fabra",
        position: "side",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 21,
    },
    {
        name: "Jorge Figal",
        position: "side",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 22,
    },
    {
        name: "Milton Casco",
        position: "side",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 23,
    },
];

export const defenders = [
    {
        name: "Paulo Diaz",
        position: "defender",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 25,
    },
    {
        name: "Emanuel Mammana",
        position: "defender",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 26,
    },
    {
        name: "Marcos Rojo",
        position: "defender",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 27,
    },
    {
        name: "David Luiz",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 28,
    },
    {
        name: "Leo Pereira",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 29,
    },
    {
        name: "Caetano",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 30,
    },
    {
        name: "Andre Ramalho",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 31,
    },
    {
        name: "G. Gomez",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 32,
    },
    {
        name: "Murillo",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 33,
    },
    {
        name: "Tinga",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 34,
    },
    {
        name: "Alonso",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 35,
    },
    {
        name: "Lyanco",
        position: "defender",
        club: "BRA",
        image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 36,
    },
];

export const midfielders = [
    {
        name: "Enzo Pérez",
        position: "midfielder",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 37,
    },
    {
        name: "Zaracho",
        position: "midfielder",
        club: "ARG",
        image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
        id: 38,
    },
    {
        name: "Gerson",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 39,
    },
    {
        name: "Everton Ribeiro",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 40,
    },
    {
        name: "Igor Coronado",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 41,
    },
    {
        name: "Rodrigo Garro",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 42,
    },
    {
        name: "Zé Rafael",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 43,
    },
    {
        name: "Raphael Veiga",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 44,
    },
    {
        name: "Vitor Bueno",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 45,
    },
    {
        name: "Caio Alexandre",
        position: "midfielder",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 46,
    },
    {
        name: "Fernández",
        position: "midfielder",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 47,
    },
    {
        name: "Ramírez",
        position: "midfielder",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 48,
    },
];

export const forwards = [
    {
        name: "Pedro",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 49,
    },
    {
        name: "Gabriel Barbosa (Gabigol)",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/jJ7RsvD/flarj.png",
        id: 50,
    },
    {
        name: "Memphis Depay",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 51,
    },
    {
        name: "Yuri Alberto",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
        id: 52,
    },
    {
        name: "Dudu",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 53,
    },
    {
        name: "Rony",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
        id: 54,
    },
    {
        name: "Luciano",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/nPccDYP/saopaulo-bra.png",
        id: 55,
    },
    {
        name: "Calleri",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/nPccDYP/saopaulo-bra.png",
        id: 56,
    },
    {
        name: "Moises",
        position: "forward",
        club: "BRA",
        image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
        id: 57,
    },
    {
        name: "Pochettino",
        position: "forward",
        club: "ARG",
        image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
        id: 58,
    },
    {
        name: "Borja",
        position: "forward",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 59,
    },
    {
        name: "Beltrán",
        position: "forward",
        club: "ARG",
        image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
        id: 60,
    },
];
