export const goalkeepers = [{
    name: "Weverton",
    position: "goalkeeper",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 1,
},
{
    name: "Everson",
    position: "goalkeeper",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 2,
},
{
    name: "Hugo",
    position: "goalkeeper",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 3,
},
{
    name: "Cássio",
    position: "goalkeeper",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 4,
},
{
    name: "Max Walef",
    position: "goalkeeper",
    club: "BRA",
    image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
    id: 5,
},
{
    name: "Bento",
    position: "goalkeeper",
    club: "BRA",
    image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
    id: 6,
},
{
    name: "Agustín Rossi",
    position: "goalkeeper",
    club: "ARG",
    image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
    id: 7,
},
{
    name: "Armani",
    position: "goalkeeper",
    image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
    club: "ARG",
    id: 8,
},
];

export const sides = [{
    name: "Marcos Rocha",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 10,
},
{
    name: "Piquerez",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 11,
},
{
    name: "G. Arana",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 24,
},
{
    name: "Mariano",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 12,
},
{
    name: "Matheusinho",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 13,
},
{
    name: "Filipe Luis",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",

    id: 14,
},
{
    name: "Fagner",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",

    id: 15,
},
{
    name: "Lucas Piton",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",

    id: 16,
},
{
    name: "Abner Vinícius",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",

    id: 17,
},
{
    name: "Khellven",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",

    id: 18,
},
{
    name: "Juninho Capixaba",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
    id: 19,
},
{
    name: "Yago Pikachu",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
    id: 20,
},
{
    name: "Jonathan Fabra",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
    id: 21,
},
{
    name: "Jorge Figal",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
    id: 22,
},
{
    name: "Milton Casco",
    position: "side",
    club: "BRA",
    image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
    id: 23,
},
];

export const defenders = [{
    name: "Paulo Diaz",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
    id: 25,
},
{
    name: "Emanuel Mammana",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
    id: 26,
},
{
    name: "Marcos Rojo",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
    id: 27,
},
{
    name: "David Luiz",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 28,
},
{
    name: "Pablo",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 29,
},
{
    name: "João Victor",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 30,
},
{
    name: "Gil",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 31,
},
{
    name: "G. Gomez",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 32,
},
{
    name: "Murillo",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 33,
},
{
    name: "Tinga",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
    id: 34,
},
{
    name: "Junior Alonso",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 35,
},
{
    name: "Nathan Silva",
    position: "defender",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 36,
},
];

export const midfielders = [{
    name: "R. Veiga",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 37,
},
{
    name: "Nacho",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 38,
},
{
    name: "Renato Augusto",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 39,
},
{
    name: "Arrascaeta",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 40,
},
{
    name: "Lucas Lima",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
    id: 41,
},
{
    name: "De La Cruz",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
    id: 43,
},
{
    name: "Eduardo Salvio",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
    id: 44,
},
{
    name: "Zé Rafael",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 45,
},
{
    name: "Everton Ribeiro",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 46,
},
{
    name: "Zaracho",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 47,
},
{
    name: "Willian",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 48,
},
{
    name: "David Terans",
    position: "midfielder",
    club: "BRA",
    image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
    id: 49,
},
];

export const forwards = [{
    name: "Hulk",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 51,
},
{
    name: "Dudu",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 50,
},
{
    name: "Gabriel",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 53,
},
{
    name: "Roger Guedes",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 52,
},
{
    name: "Silvio Romero",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/BVpJVHg/fortaleza.png",
    id: 54,
},
{
    name: "Ezequiel Barco",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/y644tnF/riverplate-arg.png",
    id: 55,
},
{
    name: "Benedetto",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/BCgTTqS/bocajuniors-arg.png",
    id: 56,
},
{
    name: "Bruno Henrique",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/jJ7RsvD/flarj.png",
    id: 58,
},
{
    name: "Rony",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/7J9sn4N/palmeiras.png",
    id: 57,
},
{
    name: "Ademir",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 59,
},
{
    name: "Jô",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/HYSc5JP/corinthians-bra.png",
    id: 60,
},
{
    name: "Pablo",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/48xzPTm/atleticopr-bra.png",
    id: 61,
},
{
    name: "Eduardo Vargas",
    position: "forward",
    club: "BRA",
    image: "https://i.ibb.co/10c334P/atleticomg-bra.png",
    id: 62,
},
];