import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    lineupContainer: {
        margin: 20,
        height: "70%",
    },
    sideLinesContainer: {
        backgroundColor: "#6eaa5e",
        borderColor: "white",
        borderWidth: 5,
        height: "100%",
    },
    areaMidfielder: {},
    addButton: {
        alignItems: "center",
        color: "black",
    },
    textAddButton: {
        color: "white",
        fontSize: 30,
        fontWeight: "bold",
        // textAlign: "center",
    },
    textMidfielder: {
        color: "white",
        fontWeight: "bold",
        fontSize: 60,
    },
    sectionContainer: {
        flexWrap: "wrap",
        alignItems: "flex-start",
        flexDirection: "row",
    },
    footballerCircle: {
        width: 50,
        height: 50,
        borderRadius: 50,
        backgroundColor: "#699f5a",
        margin: 10,
        shadowColor: "#171717",
        shadowOffset: { width: 2, height: 3 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        alignItems: "center",
        justifyContent: "center",
        elevation: 11,
    },
    footballer: {
        display: "flex",
        width: "20%",
        height: 80,
        alignItems: "center",
        justifyContent: "center",
    },
    playerContainer: {
        width: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    footballerName: {
        fontWeight: "bold",
        fontSize: 12,
        color: "#fff",
    },
    forwardContainer: {
        flex: 1,
        marginTop: 60,
        alignItems: "center",
    },
    midfielderContainer: {
        flex: 2,
        marginTop: 60,
        alignItems: "center",
        justifyContent: "center",
    },
    defenderContainer: {
        flex: 3,
        alignItems: "center",
        justifyContent: "center",
    },
    goalkeeperContainer: {
        alignItems: "center",
    },
    saveButtonActive: {
        // opacity: 1,
        marginTop: 30,
        width: "100%",
        height: "12%",
        backgroundColor: "#3CB371",
        justifyContent: "center",
        alignItems: "center",
        padding: 10,
        borderRadius: 12,
    },
    saveButtonDisabled: {
        // opacity: 0.5,
        marginTop: 30,
        width: "100%",
        backgroundColor: "#D3D3D3",
        justifyContent: "center",
        alignItems: "center",
        padding: 10,
        borderRadius: 12,
        height: "12%",
    },
    shareButtonActive: {
        // opacity: 1,
        marginTop: 10,
        width: "100%",
        backgroundColor: "#C7662B",
        justifyContent: "center",
        alignItems: "center",
        padding: 10,
        borderRadius: 12,
        height: "12%",
    },
    buttonDisabled: {
        // opacity: 0.5,
        marginTop: 10,
        width: "100%",
        backgroundColor: "#D3D3D3",
        justifyContent: "center",
        alignItems: "center",
        padding: 10,
        borderRadius: 12,
        height: "12%",
    },
    containerButtonDelete: {
        flexWrap: "wrap",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-end",
        width: "100%",
        margin: 8,
        paddingRight: 20,
    },
    buttonDelete: {
        backgroundColor: "#C7662B",
        width: 45,
        height: 40,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 12,
        shadowColor: "#171717",
        shadowOffset: { width: 2, height: 3 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 11,
        borderColor: "white",
        borderWidth: 1,
    },
});

export default styles;